import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1600px] dark:bg-dark bg-white dark:text-white text-dark">
        <Header/>
        {children}
        </body>
    </html>
  );
}
